### ISSUE TITLE
If there is Background and 2 or more tests, if 1 test failed the others are also marked as failed.

### ISSUE THREAD

**Issue by vitaliirymar** [reportportal/agent-java-karate#23]
**Describe the bug**
In a  scenario outline with examples, if 1 example passed and another one failed, the report shows 2 failed tests

**Steps to Reproduce**
1.  Run Scenario Outline with at least 2 Examples where one of them fails.
E.g. 
  Scenario Outline: Verify math
    Given def mathResult = < vara > + < varb >
    Then assert mathResult == < result >

    Examples:
      | vara | varb| result |
      | 2     | 2     | 4      |
      | 1     | 2     | 5       |
2. Check ReportPortal results

**Expected behavior**
ReportPortal displays 1 passed test and 1 failed test

**Actual behavior**
ReportPortal displays 2 failed tests
The passed test is marked as a failed, but without failed steps and without error log inside the steps.

**Dependency versions**
 agent-java-karate 5.0.0

![Bug_2_failed_tests_when_1_passed_and_1_failed](https://github.com/reportportal/agent-java-karate/assets/102508788/645f3c7f-bca4-4386-b9ac-7e093e13a2e0)
![Bug_2_failed_tests_when_1_passed_and_1_failed_](https://github.com/reportportal/agent-java-karate/assets/102508788/36fc70ed-2309-430f-875e-b437fc5560df)

**Comment by HardNorth** [comment]
@vitaliirymar Thanks for reporting this, but unfortunately I cannot reproduce your case. I created a separate [ test | https://github.com/reportportal/agent-java-karate/blob/b9fab3adae3ed79c1660b1b879b45a6c3596dea9/src/test/resources/feature/examples_one_failed.feature ] just for this, but it passes normally:
![Screenshot 2024-02-27 at 16 53 10](https://github.com/reportportal/agent-java-karate/assets/4364466/9180e2be-445a-47fd-a141-aad81bc21d9e)
 
Could you please isolate and share your example?

**Comment by vitaliirymar** [comment]
@HardNorth I managed to reproduce it with `Background`.

**Comment by HardNorth** [comment]
@vitaliirymar, Please provide any example. Since I also have tests covering Background functionality.

**Comment by vitaliirymar** [comment]
Update: The issue is also reproducible with 2 or more regular tests when 1 of them fails, all the other tests are marked as failed, if there is Background. E.g.:
```
Feature: Karate Scenario Examples

  Background: Set varb
    Given def varb = 2

  Scenario: Verify math 1
    Given def mathResult = 4 + varb
    Then assert mathResult == 6

  Scenario: Verify math 2
    Given def mathResult = 2 + 3
    Then assert mathResult == 4
```

**Comment by HardNorth** [comment]
Should be fixed in: https://github.com/reportportal/agent-java-karate/releases/tag/5.0.2

**Comment by vitaliirymar** [comment]
@HardNorth , the issue is still reproducible. It is related to Background.
Check these scenarios:
https://github.com/reportportal/agent-java-karate/issues/23#issuecomment-1968553150
https://github.com/reportportal/agent-java-karate/issues/23#issuecomment-1966769405
![image](https://github.com/reportportal/agent-java-karate/assets/102508788/0dda32d9-9c7f-48fb-9ff2-bd9bbb9b8cea)

**Comment by HardNorth** [comment]
@vitaliirymar Should be fixed in: https://github.com/reportportal/agent-java-karate/releases/tag/5.0.3

**Comment by vrymar** [comment]
@HardNorth thanks! It's fixed now!
